apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-generator
  namespace: default

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator-script
  namespace: default
data:
  load-generator.sh: |
    #!/bin/bash
    set -e

    echo "Starting load generator..."
    apt-get update && apt-get install -y procps iproute2 dnsutils curl
    pip install kubernetes requests pyyaml

    echo "changing directory to /workspace"
    cd /workspace

    echo "Running load-generator script..."
    while true; do
        python3 /workspace/load-generator.py
        echo "Waiting 5 minutes before next run..."
        sleep 300
    done

---

apiVersion: batch/v1
kind: Job
metadata:
  name: kubescape-load-generator
  namespace: default
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: load-generator
      restartPolicy: Never
      containers:
      - name: load-generator
        image: python:3.9-slim
        command: ["/bin/bash", "/scripts/load-generator.sh"]
        env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-auth
              key: token
        - name: FILE_WORKERS
          value: "10"
        - name: PROCESS_WORKERS
          value: "10"
        - name: DNS_WORKERS
          value: "10"
        volumeMounts:
        - name: load-generator-script
          mountPath: /scripts
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"

      volumes:
      - name: load-generator-script
        configMap:
          name: load-generator-script
          defaultMode: 0777
