apiVersion: batch/v1
kind: Job
metadata:
  name: kubescape-load-generator
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load-generator
        image: python:3.9-slim
        command:
        - "/bin/bash"
        - "-c"
        - |
          apt-get update && apt-get install -y procps iproute2 dnsutils curl
          pip install kubernetes requests pyyaml

          while true; do
            echo "Running load-generator script..."
            python3 /tmp/load-generator.py
            echo "Waiting 1 hour before next run..."
            sleep 300 # 5 minutes
          done
        env:
        - name: FILE_WORKERS
          value: "10"
        - name: PROCESS_WORKERS
          value: "10"
        - name: DNS_WORKERS
          value: "10"
